# Define the Trigger
name: Continuous Integration

on:
  push:
    branches:
      - main  # Adjust this branch name based on your project's main branch
      
# Specify the Environment
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        env:
           AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: 'eu-north-1'
           AWS_DEFAULT_OUTPUT: json
      # ... Add your existing build steps or commands here ...
      
      # Step 1: Install AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
       
       # Step 2: Configure AWS credentials
      - name: Configure AWS Credentials
        run: |
          #aws configure set aws_access_key_id AKIAWS2ZE5YLENPY2EB2
          #aws configure set aws_secret_access_key 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
          #aws configure set default.region eu-north-1
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
          aws configure list

      # Step 3: Upload artifacts to S3
      - name: Upload artifacts to S3
        run: |
          # Replace '.' with the path to your build artifacts
          # aws s3 sync . s3://staticwebpageassignment4
          echo "test"

      # ... Add more steps if needed ...
